// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI0gfqYRY1UHf_eyymGs2MG-tx6w9QAd0',
    appId: '1:157726663436:web:1da010aeeb9643c4971f29',
    messagingSenderId: '157726663436',
    projectId: 'groovy-scarab-426302-b9',
    authDomain: 'groovy-scarab-426302-b9.firebaseapp.com',
    storageBucket: 'groovy-scarab-426302-b9.appspot.com',
    measurementId: 'G-20CS3S3RX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ashqm6u9aoitXn7EpMWzubpD3dAPfYw',
    appId: '1:157726663436:android:58493d515237550c971f29',
    messagingSenderId: '157726663436',
    projectId: 'groovy-scarab-426302-b9',
    storageBucket: 'groovy-scarab-426302-b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvtI-4nCSWobAhMcY0anshBM6noVwZsdg',
    appId: '1:157726663436:ios:43eed6eaffdb8eb0971f29',
    messagingSenderId: '157726663436',
    projectId: 'groovy-scarab-426302-b9',
    storageBucket: 'groovy-scarab-426302-b9.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvtI-4nCSWobAhMcY0anshBM6noVwZsdg',
    appId: '1:157726663436:ios:43eed6eaffdb8eb0971f29',
    messagingSenderId: '157726663436',
    projectId: 'groovy-scarab-426302-b9',
    storageBucket: 'groovy-scarab-426302-b9.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI0gfqYRY1UHf_eyymGs2MG-tx6w9QAd0',
    appId: '1:157726663436:web:4c9b83767be86921971f29',
    messagingSenderId: '157726663436',
    projectId: 'groovy-scarab-426302-b9',
    authDomain: 'groovy-scarab-426302-b9.firebaseapp.com',
    storageBucket: 'groovy-scarab-426302-b9.appspot.com',
    measurementId: 'G-P9M8YE3RR9',
  );
}
